name: Executa em push e por agendamento

on:
  push:
    branches:
      - main  # Ou outra branch que desejar
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  exemplo-job:
    runs-on: ubuntu-latest

    steps:
      # ✅ Action pré-existente: checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # ✅ Script personalizado: Exibir data/hora e listar arquivos
      - name: Executar script personalizado
        run: |
          echo "Executando workflow personalizado"
          echo "Data e hora atual:"
          date
          echo "Listando arquivos no repositório:"
          ls -la
